[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run demo:build"

[[redirects]]
  from = "/composable-vue/*"
  to = "/composable-vue/index.html"
  status = 200

[[redirects]]
  from = "/starter/*"
  to = "/starter/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://sli.dev/"
  status = 301
  force = true
